/*
 * This file is part of FuturePlanFreeRoam.
 * 
 * FuturePlanFreeRoam is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * FuturePlanFreeRoam is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with FuturePlanFreeRoam.  If not, see <https://www.gnu.org/licenses/>.
 */

using System;
using System.Collections.Generic;
using System.Linq;

using CitizenFX.Core;
using CitizenFX.Core.Native;


namespace WeaponOnBackClient
{

public static class WeaponInfo
{
    public static readonly Dictionary<string, WeaponHash> WeaponNameWeaponHashHash = new Dictionary<string, WeaponHash>
    {
        {"WEAPON_UNARMED", WeaponHash.Unarmed},
//        {"WEAPON_ANIMAL", },
//        {"WEAPON_COUGAR", },
        {"WEAPON_KNIFE", WeaponHash.Knife},
        {"WEAPON_NIGHTSTICK", WeaponHash.Nightstick},
        {"WEAPON_HAMMER", WeaponHash.Hammer},
        {"WEAPON_BAT", WeaponHash.Bat},
        {"WEAPON_GOLFCLUB", WeaponHash.GolfClub},
        {"WEAPON_CROWBAR", WeaponHash.Crowbar},
        {"WEAPON_PISTOL", WeaponHash.Pistol},
        {"WEAPON_COMBATPISTOL", WeaponHash.CombatPistol},
        {"WEAPON_APPISTOL", WeaponHash.APPistol},
        {"WEAPON_PISTOL50", WeaponHash.Pistol50},
        {"WEAPON_MICROSMG", WeaponHash.MicroSMG},
        {"WEAPON_SMG", WeaponHash.SMG},
        {"WEAPON_ASSAULTSMG", WeaponHash.AssaultSMG},
        {"WEAPON_ASSAULTRIFLE", WeaponHash.AssaultRifle},
        {"WEAPON_CARBINERIFLE", WeaponHash.CarbineRifle},
        {"WEAPON_ADVANCEDRIFLE", WeaponHash.AdvancedRifle},
        {"WEAPON_MG", WeaponHash.MG},
        {"WEAPON_COMBATMG", WeaponHash.CombatMG},
        {"WEAPON_PUMPSHOTGUN", WeaponHash.PumpShotgun},
        {"WEAPON_SAWNOFFSHOTGUN", WeaponHash.SawnOffShotgun},
        {"WEAPON_ASSAULTSHOTGUN", WeaponHash.AssaultShotgun},
        {"WEAPON_BULLPUPSHOTGUN", WeaponHash.BullpupShotgun},
        {"WEAPON_STUNGUN", WeaponHash.StunGun},
        {"WEAPON_SNIPERRIFLE", WeaponHash.SniperRifle},
        {"WEAPON_HEAVYSNIPER", WeaponHash.HeavySniper},
//        {"WEAPON_REMOTESNIPER", },
        {"WEAPON_GRENADELAUNCHER", WeaponHash.GrenadeLauncher},
        {"WEAPON_GRENADELAUNCHER_SMOKE", WeaponHash.GrenadeLauncherSmoke},
        {"WEAPON_RPG", WeaponHash.RPG},
//        {"WEAPON_PASSENGER_ROCKET", },
//        {"WEAPON_AIRSTRIKE_ROCKET", },
//        {"WEAPON_STINGER", },
        {"WEAPON_MINIGUN", WeaponHash.Minigun},
        {"WEAPON_GRENADE", WeaponHash.Grenade},
        {"WEAPON_STICKYBOMB", WeaponHash.StickyBomb},
        {"WEAPON_SMOKEGRENADE", WeaponHash.SmokeGrenade},
        {"WEAPON_BZGAS", WeaponHash.BZGas},
        {"WEAPON_MOLOTOV", WeaponHash.Molotov},
        {"WEAPON_FIREEXTINGUISHER", WeaponHash.FireExtinguisher},
        {"WEAPON_PETROLCAN", WeaponHash.PetrolCan},
//        {"WEAPON_DIGISCANNER", },
        {"GADGET_NIGHTVISION", WeaponHash.NightVision},
        {"GADGET_PARACHUTE", WeaponHash.Parachute},
//        {"OBJECT", },
//        {"WEAPON_BRIEFCASE", },
//        {"WEAPON_BRIEFCASE_02", },
        {"WEAPON_BALL", WeaponHash.Ball},
        {"WEAPON_FLARE", WeaponHash.Flare},
//        {"VEHICLE_WEAPON_TANK", },
//        {"VEHICLE_WEAPON_SPACE_ROCKET", },
//        {"VEHICLE_WEAPON_PLANE_ROCKET", },
//        {"VEHICLE_WEAPON_PLAYER_LASER", },
//        {"VEHICLE_WEAPON_PLAYER_BULLET", },
//        {"VEHICLE_WEAPON_PLAYER_BUZZARD", },
//        {"VEHICLE_WEAPON_PLAYER_HUNTER", },
//        {"VEHICLE_WEAPON_PLAYER_LAZER", },
//        {"VEHICLE_WEAPON_ENEMY_LASER", },
//        {"VEHICLE_WEAPON_SEARCHLIGHT", },
//        {"VEHICLE_WEAPON_RADAR", },
//        {"WEAPON_VEHICLE_ROCKET", },
//        {"WEAPON_BARBED_WIRE", ""},
//        {"WEAPON_DROWNING", ""},
//        {"WEAPON_DROWNING_IN_VEHICLE", ""},
//        {"WEAPON_BLEEDING", ""},
//        {"WEAPON_ELECTRIC_FENCE", ""},
//        {"WEAPON_EXPLOSION", ""},
//        {"WEAPON_FALL", ""},
//        {"WEAPON_EXHAUSTION", ""},
//        {"WEAPON_HIT_BY_WATER_CANNON", ""},
//        {"WEAPON_RAMMED_BY_CAR", ""},
//        {"WEAPON_RUN_OVER_BY_CAR", ""},
//        {"WEAPON_HELI_CRASH", ""},
//        {"VEHICLE_WEAPON_ROTORS", ""},
//        {"WEAPON_FIRE", ""},
//        {"WEAPON_ANIMAL_RETRIEVER", ""},
//        {"WEAPON_SMALL_DOG", ""},
//        {"WEAPON_TIGER_SHARK", ""},
//        {"WEAPON_HAMMERHEAD_SHARK", ""},
//        {"WEAPON_KILLER_WHALE", ""},
//        {"WEAPON_BOAR", ""},
//        {"WEAPON_PIG", ""},
//        {"WEAPON_COYOTE", ""},
//        {"WEAPON_DEER", ""},
//        {"WEAPON_HEN", ""},
//        {"WEAPON_RABBIT", ""},
//        {"WEAPON_CAT", ""},
//        {"WEAPON_COW", ""},
//        {"WEAPON_BIRD_CRAP", },
    };

    
    public static readonly Dictionary<string, string> WeaponModel = new Dictionary<string, string>
    {
        {"WEAPON_UNARMED", ""},
        {"WEAPON_ANIMAL", ""},
        {"WEAPON_COUGAR", ""},
        {"WEAPON_KNIFE", "w_me_knife_01"},
        {"WEAPON_NIGHTSTICK", "w_me_nightstick"},
        {"WEAPON_HAMMER", "w_me_hammer"},
        {"WEAPON_BAT", "w_me_bat"},
        {"WEAPON_GOLFCLUB", "w_me_gclub"},
        {"WEAPON_CROWBAR", "w_me_crowbar"},
        {"WEAPON_PISTOL", "W_PI_PISTOL"},
        {"WEAPON_COMBATPISTOL", "W_PI_COMBATPISTOL"},
        {"WEAPON_APPISTOL", "W_PI_APPISTOL"},
        {"WEAPON_PISTOL50", "W_PI_PISTOL50"},
        {"WEAPON_MICROSMG", "w_sb_microsmg"},
        {"WEAPON_SMG", "w_sb_smg"},
        {"WEAPON_ASSAULTSMG", "w_sb_assaultsmg"},
        {"WEAPON_ASSAULTRIFLE", "W_AR_ASSAULTRIFLE"},
        {"WEAPON_CARBINERIFLE", "W_AR_CARBINERIFLE"},
        {"WEAPON_ADVANCEDRIFLE", "W_AR_ADVANCEDRIFLE"},
        {"WEAPON_MG", "w_mg_mg"},
        {"WEAPON_COMBATMG", "w_mg_combatmg"},
        {"WEAPON_PUMPSHOTGUN", "w_sg_pumpshotgun"},
        {"WEAPON_SAWNOFFSHOTGUN", "w_sg_sawnoff"},
        {"WEAPON_ASSAULTSHOTGUN", "w_sg_assaultshotgun"},
        {"WEAPON_BULLPUPSHOTGUN", "w_sg_bullpupshotgun"},
        {"WEAPON_STUNGUN", "w_pi_stungun"},
        {"WEAPON_SNIPERRIFLE", "w_sr_sniperrifle"},
        {"WEAPON_HEAVYSNIPER", "w_sr_heavysniper"},
        {"WEAPON_REMOTESNIPER", ""},
        {"WEAPON_GRENADELAUNCHER", "w_lr_grenadelauncher"},
        {"WEAPON_GRENADELAUNCHER_SMOKE", "w_lr_grenadelauncher"},
        {"WEAPON_RPG", "w_lr_rpg"},
        {"WEAPON_PASSENGER_ROCKET", "w_lr_rpg"},
        {"WEAPON_AIRSTRIKE_ROCKET", "w_lr_rpg"},
        {"WEAPON_STINGER", "w_lr_rpg"},
        {"WEAPON_MINIGUN", "w_mg_minigun"},
        {"WEAPON_GRENADE", "w_ex_grenadefrag"},
        {"WEAPON_STICKYBOMB", "w_ex_pe"},
        {"WEAPON_SMOKEGRENADE", "w_ex_grenadesmoke"},
        {"WEAPON_BZGAS", "w_ex_grenadesmoke"},
        {"WEAPON_MOLOTOV", "w_ex_molotov"},
        {"WEAPON_FIREEXTINGUISHER", "w_am_fire_exting"},
        {"WEAPON_PETROLCAN", "w_am_jerrycan"},
        {"WEAPON_DIGISCANNER", "w_am_digiscanner"},
        {"GADGET_NIGHTVISION", ""},
        {"GADGET_PARACHUTE", ""},
        {"OBJECT", ""},
        {"WEAPON_BRIEFCASE", "w_am_case"},
        {"WEAPON_BRIEFCASE_02", "w_am_brfcase"},
        {"WEAPON_BALL", "w_am_baseball"},
        {"WEAPON_FLARE", "w_am_flare"},
        {"VEHICLE_WEAPON_TANK", ""},
        {"VEHICLE_WEAPON_SPACE_ROCKET", ""},
        {"VEHICLE_WEAPON_PLANE_ROCKET", ""},
        {"VEHICLE_WEAPON_PLAYER_LASER", ""},
        {"VEHICLE_WEAPON_PLAYER_BULLET", ""},
        {"VEHICLE_WEAPON_PLAYER_BUZZARD", ""},
        {"VEHICLE_WEAPON_PLAYER_HUNTER", ""},
        {"VEHICLE_WEAPON_PLAYER_LAZER", ""},
        {"VEHICLE_WEAPON_ENEMY_LASER", ""},
        {"VEHICLE_WEAPON_SEARCHLIGHT", ""},
        {"VEHICLE_WEAPON_RADAR", ""},
        {"WEAPON_VEHICLE_ROCKET", "w_lr_rpg"},
        {"WEAPON_BARBED_WIRE", ""},
        {"WEAPON_DROWNING", ""},
        {"WEAPON_DROWNING_IN_VEHICLE", ""},
        {"WEAPON_BLEEDING", ""},
        {"WEAPON_ELECTRIC_FENCE", ""},
        {"WEAPON_EXPLOSION", ""},
        {"WEAPON_FALL", ""},
        {"WEAPON_EXHAUSTION", ""},
        {"WEAPON_HIT_BY_WATER_CANNON", ""},
        {"WEAPON_RAMMED_BY_CAR", ""},
        {"WEAPON_RUN_OVER_BY_CAR", ""},
        {"WEAPON_HELI_CRASH", ""},
        {"VEHICLE_WEAPON_ROTORS", ""},
        {"WEAPON_FIRE", ""},
        {"WEAPON_ANIMAL_RETRIEVER", ""},
        {"WEAPON_SMALL_DOG", ""},
        {"WEAPON_TIGER_SHARK", ""},
        {"WEAPON_HAMMERHEAD_SHARK", ""},
        {"WEAPON_KILLER_WHALE", ""},
        {"WEAPON_BOAR", ""},
        {"WEAPON_PIG", ""},
        {"WEAPON_COYOTE", ""},
        {"WEAPON_DEER", ""},
        {"WEAPON_HEN", ""},
        {"WEAPON_RABBIT", ""},
        {"WEAPON_CAT", ""},
        {"WEAPON_COW", ""},
        {"WEAPON_BIRD_CRAP", "w_ex_birdshat"},
    };
    
    public static readonly Dictionary<string, string> WeaponNames = new Dictionary<string, string>
    {
        { "weapon_advancedrifle", API.GetLabelText("WT_RIFLE_ADV") },
        { "weapon_appistol", API.GetLabelText("WT_PIST_AP") },
        { "weapon_assaultrifle", API.GetLabelText("WT_RIFLE_ASL") },
        { "weapon_assaultshotgun", API.GetLabelText("WT_SG_ASL") },
        { "weapon_assaultsmg", API.GetLabelText("WT_MG_ASL") },
        { "weapon_autoshotgun", API.GetLabelText("WT_AUTOSHOT") },
        { "weapon_bat", API.GetLabelText("WT_BAT") },
        { "weapon_ball", API.GetLabelText("WT_BALL") },
        { "weapon_battleaxe", API.GetLabelText("WT_BAXE") },
        { "weapon_bottle", API.GetLabelText("WT_BOTTLE") },
        { "weapon_bullpuprifle", API.GetLabelText("WT_BULLPUPRFL") },
        { "weapon_bullpupshotgun", API.GetLabelText("WT_SG_BLP") },
        { "weapon_bzgas", API.GetLabelText("WT_BZGAS") },
        { "weapon_carbinerifle", API.GetLabelText("WT_RIFLE_CBN") },
        { "weapon_combatmg", API.GetLabelText("WT_MG_CBT") },
        { "weapon_combatpdw", API.GetLabelText("WT_COMBATPDW") },
        { "weapon_combatpistol", API.GetLabelText("WT_PIST_CBT") },
        { "weapon_compactlauncher", API.GetLabelText("WT_CMPLAUNC") },
        { "weapon_compactrifle", API.GetLabelText("WT_SG_COMPR") },
        { "weapon_crowbar", API.GetLabelText("WT_CROWBAR") },
        { "weapon_dagger", API.GetLabelText("WT_DAGGER") },
        { "weapon_dbshotgun", API.GetLabelText("WT_SG_BBSHOT") },
        { "weapon_fireextinguisher", API.GetLabelText("WT_FIRE") },
        { "weapon_firework", API.GetLabelText("WT_FWRKLNCHR") },
        { "weapon_flare", API.GetLabelText("WT_FLARE") },
        { "weapon_flaregun", API.GetLabelText("WT_FLAREGUN") },
        { "weapon_flashlight", API.GetLabelText("WT_FLASHLIGHT") },
        { "weapon_golfclub", API.GetLabelText("WT_GOLFCLUB") },
        { "weapon_grenade", API.GetLabelText("WT_GNADE") },
        { "weapon_grenadelauncher", API.GetLabelText("WT_GL") },
        { "weapon_gusenberg", API.GetLabelText("WT_GUSENBERG") },
        { "weapon_hammer", API.GetLabelText("WT_HAMMER") },
        { "weapon_hatchet", API.GetLabelText("WT_HATCHET") },
        { "weapon_heavypistol", API.GetLabelText("WT_HEAVYPSTL") },
        { "weapon_heavyshotgun", API.GetLabelText("WT_HVYSHOT") },
        { "weapon_heavysniper", API.GetLabelText("WT_SNIP_HVY") },
        { "weapon_hominglauncher", API.GetLabelText("WT_HOMING") },
        { "weapon_knife", API.GetLabelText("WT_KNIFE") },
        { "weapon_knuckle", API.GetLabelText("WT_KNUCKLE") },
        { "weapon_machete", API.GetLabelText("WT_MACHETE") },
        { "weapon_machinepistol", API.GetLabelText("WT_MACHPIST") },
        { "weapon_marksmanpistol", API.GetLabelText("WT_MKPISTOL") },
        { "weapon_marksmanrifle", API.GetLabelText("WT_MKRIFLE") },
        { "weapon_mg", API.GetLabelText("WT_MG") },
        { "weapon_microsmg", API.GetLabelText("WT_SMG_MCR") },
        { "weapon_minigun", API.GetLabelText("WT_MINIGUN") },
        { "weapon_minismg", API.GetLabelText("WT_MINISMG") },
        { "weapon_molotov", API.GetLabelText("WT_MOLOTOV") },
        { "weapon_musket", API.GetLabelText("WT_MUSKET") },
        { "weapon_nightstick", API.GetLabelText("WT_NGTSTK") },
        { "weapon_petrolcan", API.GetLabelText("WT_PETROL") },
        { "weapon_pipebomb", API.GetLabelText("WT_PIPE") },
        { "weapon_pistol", API.GetLabelText("WT_PIST") },
        { "weapon_pistol50", API.GetLabelText("WT_PIST_50") },
        { "weapon_poolcue", API.GetLabelText("WT_POOLQ") },
        { "weapon_proxmine", API.GetLabelText("WT_PROXIM") },
        { "weapon_pumpshotgun", API.GetLabelText("WT_SG_PMP") },
        { "weapon_railgun", API.GetLabelText("WT_RAILGUN") },
        { "weapon_revolver", API.GetLabelText("WT_REVLVR") },
        { "weapon_rpg", API.GetLabelText("WT_RPG") },
        { "weapon_sawnoffshotgun", API.GetLabelText("WT_SG_SOF") },
        { "weapon_smg", API.GetLabelText("WT_SMG") },
        { "weapon_smokegrenade", API.GetLabelText("WT_GNADE_SMK") },
        { "weapon_sniperrifle", API.GetLabelText("WT_SNIP_RIF") },
        { "weapon_snowball", API.GetLabelText("WT_SNWBALL") },
        { "weapon_snspistol", API.GetLabelText("WT_SNSPISTOL") },
        { "weapon_specialcarbine", API.GetLabelText("WT_RIFLE_SCBN") },
        { "weapon_stickybomb", API.GetLabelText("WT_GNADE_STK") },
        { "weapon_stungun", API.GetLabelText("WT_STUN") },
        { "weapon_switchblade", API.GetLabelText("WT_SWTCHBLDE") },
        { "weapon_unarmed", API.GetLabelText("WT_UNARMED") },
        { "weapon_vintagepistol", API.GetLabelText("WT_VINTPSTL") },
        { "weapon_wrench", API.GetLabelText("WT_WRENC") },
        //mpgunrunning
        { "weapon_pistol_mk2", API.GetLabelText("WT_PIST2") },
        { "weapon_assaultrifle_mk2", API.GetLabelText("WT_RIFLE_ASL2") },
        { "weapon_carbinerifle_mk2", API.GetLabelText("WT_RIFLE_CBN2") },
        { "weapon_combatmg_mk2", API.GetLabelText("WT_MG_CBT2") },
        { "weapon_heavysniper_mk2", API.GetLabelText("WT_SNIP_HVY2") },
        { "weapon_smg_mk2", API.GetLabelText("WT_SMG2") },
        //The Doomsday Heist Update
        { "weapon_snspistol_mk2", API.GetLabelText("WT_SNSPISTOL2") },
        { "weapon_revolver_mk2", API.GetLabelText("WT_REVOLVER2") },
        { "weapon_specialcarbine_mk2", API.GetLabelText("WT_SPCARBINE2") },
        { "weapon_bullpuprifle_mk2", API.GetLabelText("WT_BULLRIFLE2") },
        { "weapon_pumpshotgun_mk2", API.GetLabelText("WT_SG_PMP2") },
        { "weapon_marksmanrifle_mk2", API.GetLabelText("WT_MKRIFLE2") },
        { "weapon_doubleaction", API.GetLabelText("WT_REV_DA") },
        // DLC CHRISTMAS2018 (v 1604)
        { "weapon_raypistol", API.GetLabelText("WT_RAYPISTOL") },
        { "weapon_raycarbine", API.GetLabelText("WT_RAYCARBINE") },
        { "weapon_rayminigun", API.GetLabelText("WT_RAYMINIGUN") },
        { "weapon_stone_hatchet", API.GetLabelText("WT_SHATCHET") }
    };

    public static List<WeaponHash> GetWeaponHashes()
	    => WeaponNames.Keys.Select(wn => (WeaponHash) (uint) API.GetHashKey(wn)).ToList();
    
}


}